非同期通信、自動更新機能実装
tana1818/chat-space2 pull request #4
Opened 2019-02-17 11:20 UTC by tana1818

2019-02-17 11:21 UTC, tana1818 commented
非同期通信、自動更新機能の実装

2019-02-17 11:22 UTC, tana1818 commented
確認お願いします

2019-02-17 11:27 UTC, ghost requested changes
キャッシュファイルはpushしないようにしましょう

2019-02-17 11:27 UTC, hiroki5123 commented on tmp/cache/assets/sprockets/v3.0/x7/x7PYh8DJvPykcEqpVab2vcY9-GFz-3cqtoMlRAu94Uc.cache
> +x��VAO�0�
このファイルはpushしないでください。

2019-02-17 11:29 UTC, ghost requested changes

2019-02-17 11:29 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +  //
ここ削除しましょう

2019-02-17 11:29 UTC, hiroki5123 commented on app/views/messages/index.json.jbuilder
> +#   json.user_name  new_message.user.name
使用していないのであれば、削除しましょう

2019-02-17 11:29 UTC, hiroki5123 commented on app/views/messages/create.json.jbuilder
> +# binding.pry
削除しましょう

2019-02-17 11:29 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +        return false
ここでfalseを返しているのはなぜですか？

2019-02-17 11:30 UTC, hiroki5123 commented
自動更新の挙動を確認したいので、２つのブラウザを開いて自動更新を動かすところをGIFでこちらに添付してください。

2019-02-17 11:35 UTC, tana1818 commented on app/assets/javascripts/message.js
> +        return false
else時に何を書けばいいかわからなかったです

2019-02-17 11:35 UTC, tana1818 commented on app/assets/javascripts/message.js
> +  //
ここを消すと非同期通信ではない挙動をしてしまうのですが、、

2019-02-18 07:54 UTC, tana1818 commented
https://s17.aconvert.com/convert/p3r68-cdx67/jz6bs-ghzki.gif

2019-02-18 07:55 UTC, tana1818 commented
chat-space完成しました
確認お願いします

2019-02-18 07:57 UTC, TOMARUMARU reviewed
tmp以下gitignoreしてPRに上がらないようにしてください

2019-02-18 07:57 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +    if (message.image.url) {
三項演算子で書きましょう

2019-02-18 07:57 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
reset使いましょう

2019-02-18 08:23 UTC, ghost reviewed
キャッシュファイルが残っているのでレビュー申請を出す前に必ず Files changed を確認して、キャッシュファイルが変更差分に入っていないことを確認し手からレビュー申請をお願い致します。

2019-02-18 08:23 UTC, hiroki5123 commented on tmp/cache/assets/sprockets/v3.0/x7/x7PYh8DJvPykcEqpVab2vcY9-GFz-3cqtoMlRAu94Uc.cache
> +x��VAO�0�
こちらのファイルは削除しましょう

2019-02-18 08:23 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
こちら修正をお願い致します。

2019-02-18 08:23 UTC, hiroki5123 commented on app/assets/javascripts/message.js
> +    if (message.image.url) {
こちらも修正をお願い致します。

2019-02-18 08:23 UTC, tana1818 commented
ignoreの書き方はあってますでしょうか？

2019-02-18 08:30 UTC, tana1818 commented
casheはデータの記録的なフォルダなんでしょうか
v3.0のフォルダごと消してしまっていいんでしょうか？

2019-02-18 08:33 UTC, TOMARUMARU commented
差分に上がらなければgitignoreができていることになりますので、ご確認ください。
cacheファイルは消してしまって大丈夫です

2019-02-18 08:42 UTC, tana1818 commented
三項演算子がイマイチわからないのですが、どう直せばいいですか

2019-02-18 08:45 UTC, yusukeyamane commented on app/assets/javascripts/message.js
> +    if (message.image.url) {
> addImage = message.image.url ? `<img src="${message.image.url}" class="lower-message__image">` : '';

のような感じですかね。動作確認はしてないのでこのコードを元に調整してみてください

2019-02-18 08:47 UTC, yusukeyamane commented on app/assets/javascripts/message.js
> +        return false
であればelseの記述自体不要では無いでしょうか？

2019-02-18 08:48 UTC, yusukeyamane commented
cacheディレクトリ以下削除をお願いします

2019-02-18 08:48 UTC, yusukeyamane commented
いくつか前回のコメントの見逃しがあるので、再度確認お願いします

2019-02-18 11:15 UTC, tana1818 commented
三項演算子、reset訂正しました
確認お願いします

2019-02-18 11:18 UTC, TOMARUMARU commented
cacheファイル消えていないです。みていただければわかりますが上がってきているファイルが1200あります。

2019-02-18 11:32 UTC, tana1818 commented
一回消したんですけど、再度何かメッセージを送るとcasheファイルが作成されます
ただgitignoreで#tmpを記載したのでそれ以来gitには反映されなくなりました
これでも何かおかしいですか？

2019-02-18 11:36 UTC, ghost reviewed
Files changedにはこのプルリクエストで1200のファイルが変更されていると表示されていますので、ローカルではなくリモートの変更差分を確認してください。

2019-02-18 11:37 UTC, hiroki5123 commented
わからなければ、TECH::CONNECTで質問をお願い致します。

2019-02-18 12:21 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
こちら、`$('.form__message').reset()`としましょう！

2019-02-18 12:21 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +    $(function() {
50-51行目はこのファイルの1行目とかぶっているので消しておいてください。
ちなみに、これは`$(document).on('ready', function() {`の省略記法です。これはdocumentが読み込まれたら、以下の記述が実行されるということです。

2019-02-18 12:21 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +      }
71-77行目までのインデントを半角スペース２つ分深くしましょう。

2019-02-18 12:21 UTC, kuroko918 commented on app/views/messages/create.json.jbuilder
> +json.image  @message.image
`@message.image`を`@message.image.url`としましょう！
railsでを使用しているので、フロントエンドで処理するより、サーバーサイド側で処理する方が処理速度速いです。

2019-02-18 12:21 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +      addImage = message.image.url ? `<img src="${message.image.url}" class="lower-message__image">` : "";
それに伴い、`addImage = message.image ? `<img src=${message.image} class="lower-message__image">` : "";`としましょう！
一部いらないダブルクオーテーションを消しておきました。

2019-02-18 12:21 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +       else {
59-60行目をまとめて、`} else {`としましょう！
これがjavascriptのelseの書き方です。

2019-02-18 12:21 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +    e.stopPropagation();
47行目に`return false`と記述してあるのですが、そちらが原因で、バブリングが起きているかと思います。
`return false`を無くせば、`e.stopPropagation();`はいらないかと思いますが、いかがでしょうか？
一度確認お願いします。

2019-02-18 12:42 UTC, tana1818 commented
resetのとこだけうまく行きませんがそれ以外はうまくいきました
今の所エラーなく自動更新、非同期通信は動きます
確認お願いします

2019-02-18 12:46 UTC, TOMARUMARU commented
> Files changedにはこのプルリクエストで1200のファイルが変更されていると表示されていますので、ローカルではなくリモートの変更差分を確認してください。

こちら修正されていません

2019-02-18 13:06 UTC, kuroko918 commented
> resetのとこだけうまく行きませんがそれ以外はうまくいきました
> 今の所エラーなく自動更新、非同期通信は動きます
> 確認お願いします

では、resetに変更しなくて結構です。
cacheの件は大丈夫ですので、このままマージして次に進んでください。

2019-02-18 13:11 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +    // return false
これはいらないので消しておきましょう

2019-02-18 13:11 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +    e.stopPropagation();
これも消しましょう

2019-02-18 13:11 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +       else {
こちらも修正しましょう・

2019-02-18 13:11 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +        // clearInterval();
こちらは使いますか？
おそらく必要かと思います。
ただ、ここではないと思います。

2019-02-18 13:11 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +          $.each(data, function(i, data){
iはいらないと思います。

2019-02-18 13:11 UTC, kuroko918 commented on app/assets/javascripts/message.js
> +          if (data.length){
インデントを揃えてください。

2019-02-19 01:52 UTC, tana1818 commented on app/assets/javascripts/message.js
> +    e.stopPropagation();
e.stopPropagation();
を消すと最初のメッセージは遅れるのですが、
それ以降のメッセージがなぜか送れなくなります
railsの特性なのか、自分のコードミスなのかわかりません

2019-02-19 03:12 UTC, tana1818 commented on app/assets/javascripts/message.js
> +    e.stopPropagation();
e.stopPropagation();を消すと最初のメッセージは送信されるのですが
それ以降のメッセージが送れなくなります
rails の特性なのか自分のコードミスなのかわかりません

2019-02-19 03:13 UTC, tana1818 commented on app/assets/javascripts/message.js
> +          $.each(data, function(i, data){
消去しました

2019-02-19 03:13 UTC, tana1818 commented on app/assets/javascripts/message.js
> +          if (data.length){
一応揃えました
確認お願いします

2019-02-19 05:00 UTC, tana1818 commented on app/assets/javascripts/message.js
> +        // clearInterval();
修正しました確認お願いします

2019-02-19 05:14 UTC, miyagit commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
こちら修正が反映されていないので反映してください。

2019-02-19 05:27 UTC, tana1818 commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
kuroko918さんに
下のコメントでresetは直さなくていいと言ってくれたのですが、、

2019-02-19 05:43 UTC, hirozak commented on app/assets/javascripts/message.js
> +    e.stopPropagation();
ボタンにdisabled要素入ってませんか？
それを取り除く処理をしましょう

2019-02-19 05:48 UTC, miyagit commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
すみません、見落としてました。ではresetは使わなくて大丈夫です。

2019-02-19 07:06 UTC, tana1818 commented on app/assets/javascripts/message.js
> +    e.stopPropagation();
disabled要素は書いてないです

2019-02-19 08:48 UTC, tana1818 commented on app/assets/javascripts/message.js
> +    e.stopPropagation();
return falseで書き直しました

2019-02-19 08:50 UTC, tana1818 commented on tmp/cache/assets/sprockets/v3.0/x7/x7PYh8DJvPykcEqpVab2vcY9-GFz-3cqtoMlRAu94Uc.cache
> +x��VAO�0�
済み

2019-02-19 08:50 UTC, tana1818 commented on app/assets/javascripts/message.js
> +  //
済み

2019-02-19 08:50 UTC, tana1818 commented on app/views/messages/index.json.jbuilder
> +#   json.user_name  new_message.user.name
済み

2019-02-19 08:50 UTC, tana1818 commented on app/views/messages/create.json.jbuilder
> +# binding.pry
済み

2019-02-19 08:50 UTC, tana1818 commented on app/assets/javascripts/message.js
> +    if (message.image.url) {
済み

2019-02-19 08:51 UTC, tana1818 commented on app/assets/javascripts/message.js
> +        return false
済み

2019-02-19 08:51 UTC, tana1818 commented on app/assets/javascripts/message.js
> +      $('.form__message').val('');
済み

2019-02-19 08:52 UTC, tana1818 commented on app/assets/javascripts/message.js
> +    $(function() {
済み

2019-02-19 08:52 UTC, tana1818 commented on app/assets/javascripts/message.js
> +      }
済み

2019-02-19 08:52 UTC, tana1818 commented on app/views/messages/create.json.jbuilder
> +json.image  @message.image
済み

2019-02-19 08:52 UTC, tana1818 commented on app/assets/javascripts/message.js
> +      addImage = message.image.url ? `<img src="${message.image.url}" class="lower-message__image">` : "";
済み

2019-02-19 08:53 UTC, tana1818 commented on app/assets/javascripts/message.js
> +    // return false
済み

2019-02-19 08:58 UTC, TOMARUMARU approved these changes
LGTM

2019-02-19 09:36 UTC, merged