Takahashi
tana1818/chat-space2 pull request #5
Opened 2019-02-21 09:53 UTC by tana1818

インクリメンタルサーチ実装

2019-02-21 11:13 UTC, tana1818 commented
インクリメンタルサーチの実装と
logファイルを読み込まないようにターミナルから設定

2019-02-21 11:14 UTC, tana1818 commented
インクリメンタルサーチの実装と
logファイルがgit hubに読み込まれないようにターミナルから設定した

2019-02-21 11:17 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +<<<<<<< HEAD
コンフリクト解消しましょう

2019-02-21 11:17 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +      // $('#message_content').val('');
こちらは消しましょう

2019-02-21 11:17 UTC, TOMARUMARU commented on app/assets/javascripts/message.js
> +          $('chat__messages').append(html);
こちら正常に動きますか？

2019-02-21 11:17 UTC, TOMARUMARU commented on app/assets/stylesheets/modules/_new_groups.scss
> +    .chat-group-user__name {
&使いましょう。他の箇所も同様です

2019-02-21 11:17 UTC, TOMARUMARU commented on app/controllers/users_controller.rb
> +  # binding.pry
消しましょう

2019-02-21 11:38 UTC, tana1818 commented on app/assets/javascripts/message.js
> +<<<<<<< HEAD
削除

2019-02-21 11:38 UTC, tana1818 commented on app/assets/javascripts/message.js
> +      // $('#message_content').val('');
削除

2019-02-21 11:39 UTC, tana1818 commented on app/assets/javascripts/message.js
> +          $('chat__messages').append(html);
すいません動きません！訂正しました！

2019-02-21 11:39 UTC, tana1818 commented on app/assets/stylesheets/modules/_new_groups.scss
> +    .chat-group-user__name {
訂正

2019-02-21 11:39 UTC, tana1818 commented on app/controllers/users_controller.rb
> +  # binding.pry
削除

2019-02-21 11:40 UTC, tana1818 commented
修正しました
再度確認よろしくお願いします

2019-02-21 11:46 UTC, TOMARUMARU commented
pushしてください

2019-02-21 11:48 UTC, tana1818 commented
すいません、お願いします

2019-02-21 11:52 UTC, TOMARUMARU commented on app/controllers/groups_controller.rb
> +    set_groups
update同様before_actionで呼びましょう、またset_groupsではなくset_groupの方が適切ですね！

2019-02-21 12:08 UTC, tana1818 commented
お願いします

2019-02-21 12:10 UTC, yuki-uchida requested changes

2019-02-21 12:10 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +    .done(function(data){ //非同期通信の結果として返ってくるデータは、done(function(data) { 処理 })の関数の引数で受け取る
dataでは、何を受け取ったのかわからないので、それがわかる名前に変えましょう

2019-02-21 12:10 UTC, yuki-uchida commented on app/assets/javascripts/message.js
> +      var html = buildHTML(data);//このdataはサーバーから返されたcreate.json.jbuider
buildHTMLでは、何をどうするのかがわかりづらいので、buildSendMessageHTMLとかいかがでしょうか

2019-02-21 12:36 UTC, tana1818 commented
確認お願いします

2019-02-22 02:45 UTC, hzak2xx approved these changes
LGTM

2019-02-22 07:48 UTC, merged